import { InternalEObject } from "./InternalEObject";
import { BasicNotifierImpl } from "./BasicNotifierImpl";
import { NotificationChain } from "./NotificationChain";
import { EObject } from "./EObject";
import { EClass } from "./EClass";
import { EStructuralFeature } from "./EStructuralFeature";
import { EReference } from "./EReference";
import { EList } from "./EList";
import { EOperation } from "./EOperation";
import { Resource } from "./Resource";
import { TreeIterator } from "./TreeIterator";
export declare class BasicEObjectImpl extends BasicNotifierImpl implements EObject, InternalEObject {
    _uuid: string;
    constructor();
    private static generateUUID;
    static EOPPOSITE_FEATURE_BASE: number;
    protected _eContainer: InternalEObject;
    protected _eContainerFeatureID: number;
    _eStaticClass: EClass;
    eBasicSetContainer(newContainer: InternalEObject, newContainerFeatureID: number, notifications: NotificationChain): NotificationChain;
    protected eBasicSetContainer_(newContainer: InternalEObject, newContainerFeatureID: number): void;
    eInternalContainer(): InternalEObject;
    eContainerFeatureID(): number;
    eBasicRemoveFromContainer(notifications: NotificationChain): NotificationChain;
    eGet(...args: Array<any>): any;
    eGet_EStructuralFeature_boolean_boolean(feature: EStructuralFeature, resolve: boolean, coreType: boolean): any;
    eGet_number_boolean_boolean(featureID: number, resolve: boolean, coreType: boolean): any;
    eDerivedStructuralFeatureID_EStructuralFeature(eStructuralFeature: EStructuralFeature): number;
    eDerivedStructuralFeatureID_number_Function(baseFeatureID: number, baseClass: Function): number;
    eDerivedStructuralFeatureID(...args: Array<any>): number;
    eClass(): EClass;
    protected eStaticClass(): EClass;
    eInverseAdd(...args: Array<any>): NotificationChain;
    eInverseAdd4(otherEnd: InternalEObject, featureID: number, baseClass: Function, msgs: NotificationChain): NotificationChain;
    eInverseRemove(...args: Array<any>): NotificationChain;
    eInverseAdd3(otherEnd: InternalEObject, featureID: number, msgs: NotificationChain): NotificationChain;
    eInverseRemove4(otherEnd: InternalEObject, featureID: number, baseClass: Function, msgs: NotificationChain): NotificationChain;
    eInverseRemove3(otherEnd: InternalEObject, featureID: number, msgs: NotificationChain): NotificationChain;
    eIsSet(feature: EStructuralFeature): boolean;
    eContainmentFeature(): EReference;
    eIsProxy(): boolean;
    eContainingFeature(): EStructuralFeature;
    eContainer(): EObject;
    eInvoke(operation: EOperation, args: EList<any>): any;
    eSet(feature: EStructuralFeature, newValue: any): void;
    eSet_number_any(featureId: number, newValue: any): void;
    eResource(): Resource;
    eContents(): EList<EObject>;
    eCrossReferences(): EList<EObject>;
    eAllContents(): TreeIterator<EObject>;
    eGet_EStructuralFeature(feature: EStructuralFeature): any;
    eGet_EStructuralFeature_boolean(feature: EStructuralFeature, resolve: boolean): any;
    eUnset(feature: EStructuralFeature): void;
    eURIFragmentSegment(eFeature: EStructuralFeature, eObject: EObject): string;
    eObjectForURIFragmentSegment(uriFragmentSegment: string): EObject;
    eSetClass(eClass: EClass): void;
    eBaseStructuralFeatureID(derivedFeatureID: number, baseClass: Function): number;
    eDerivedOperationID(baseOperationID: number, baseClass: Function): number;
    eResolveProxy(proxy: InternalEObject): EObject;
}
