import { EAttribute } from "./EAttribute";
import { EClass } from "./EClass";
import { EOperation } from "./EOperation";
import { EPackageImpl } from "./EPackageImpl";
import { EReference } from "./EReference";
import { EcorePackage } from "./EcorePackage";
import { EDataType } from "./EDataType";
export declare class EcorePackageImpl extends EPackageImpl implements EcorePackage {
    static eNAME: string;
    static eNS_URI: string;
    static eNS_PREFIX: string;
    static init(): EcorePackage;
    private isCreated;
    createPackageContents: () => void;
    private isInitialized;
    initializePackageContents: () => void;
    private EAttributeEClass;
    private EAnnotationEClass;
    private EClassEClass;
    private EClassifierEClass;
    private EDataTypeEClass;
    private EEnumEClass;
    private EEnumLiteralEClass;
    private EFactoryEClass;
    private EModelElementEClass;
    private ENamedElementEClass;
    private EObjectEClass;
    private EOperationEClass;
    private EPackageEClass;
    private EParameterEClass;
    private EReferenceEClass;
    private EStructuralFeatureEClass;
    private ETypedElementEClass;
    private EStringToStringMapEntryEClass;
    private EGenericTypeEClass;
    private ETypeParameterEClass;
    private EBigDecimalEDataType;
    private EBigIntegerEDataType;
    private EBooleanEDataType;
    private EBooleanObjectEDataType;
    private EByteEDataType;
    private EByteArrayEDataType;
    private EByteObjectEDataType;
    private ECharEDataType;
    private ECharacterObjectEDataType;
    private EDateEDataType;
    private EDiagnosticChainEDataType;
    private EDoubleEDataType;
    private EDoubleObjectEDataType;
    private EEListEDataType;
    private EEnumeratorEDataType;
    private EFeatureMapEDataType;
    private EFeatureMapEntryEDataType;
    private EFloatEDataType;
    private EFloatObjectEDataType;
    private EIntEDataType;
    private EIntegerObjectEDataType;
    private EJavaClassEDataType;
    private EJavaObjectEDataType;
    private ELongEDataType;
    private ELongObjectEDataType;
    private EMapEDataType;
    private EResourceEDataType;
    private EResourceSetEDataType;
    private EShortEDataType;
    private EShortObjectEDataType;
    private EStringEDataType;
    private ETreeIteratorEDataType;
    private EInvocationTargetExceptionEDataType;
    static EMODELELEMENT: number;
    static EMODELELEMENT_FEATURE_COUNT: number;
    static EMODELELEMENT_OPERATION_COUNT: number;
    static EMODELELEMENT_EANNOTATIONS: number;
    static EMODELELEMENT___GETEANNOTATION__SOURCE: number;
    static ENAMEDELEMENT: number;
    static ENAMEDELEMENT_FEATURE_COUNT: number;
    static ENAMEDELEMENT_OPERATION_COUNT: number;
    static ENAMEDELEMENT_EANNOTATIONS: number;
    static ENAMEDELEMENT_NAME: number;
    static ETYPEDELEMENT: number;
    static ETYPEDELEMENT_FEATURE_COUNT: number;
    static ETYPEDELEMENT_OPERATION_COUNT: number;
    static ETYPEDELEMENT_EANNOTATIONS: number;
    static ETYPEDELEMENT_NAME: number;
    static ETYPEDELEMENT_ORDERED: number;
    static ETYPEDELEMENT_UNIQUE: number;
    static ETYPEDELEMENT_LOWERBOUND: number;
    static ETYPEDELEMENT_UPPERBOUND: number;
    static ETYPEDELEMENT_MANY: number;
    static ETYPEDELEMENT_REQUIRED: number;
    static ETYPEDELEMENT_ETYPE: number;
    static ETYPEDELEMENT_EGENERICTYPE: number;
    static ESTRUCTURALFEATURE: number;
    static ESTRUCTURALFEATURE_FEATURE_COUNT: number;
    static ESTRUCTURALFEATURE_OPERATION_COUNT: number;
    static ESTRUCTURALFEATURE_EANNOTATIONS: number;
    static ESTRUCTURALFEATURE_NAME: number;
    static ESTRUCTURALFEATURE_ORDERED: number;
    static ESTRUCTURALFEATURE_UNIQUE: number;
    static ESTRUCTURALFEATURE_LOWERBOUND: number;
    static ESTRUCTURALFEATURE_UPPERBOUND: number;
    static ESTRUCTURALFEATURE_MANY: number;
    static ESTRUCTURALFEATURE_REQUIRED: number;
    static ESTRUCTURALFEATURE_ETYPE: number;
    static ESTRUCTURALFEATURE_EGENERICTYPE: number;
    static ESTRUCTURALFEATURE_CHANGEABLE: number;
    static ESTRUCTURALFEATURE_VOLATILE: number;
    static ESTRUCTURALFEATURE_TRANSIENT: number;
    static ESTRUCTURALFEATURE_DEFAULTVALUELITERAL: number;
    static ESTRUCTURALFEATURE_DEFAULTVALUE: number;
    static ESTRUCTURALFEATURE_UNSETTABLE: number;
    static ESTRUCTURALFEATURE_DERIVED: number;
    static ESTRUCTURALFEATURE_ECONTAININGCLASS: number;
    static ESTRUCTURALFEATURE___GETFEATUREID: number;
    static ESTRUCTURALFEATURE___GETCONTAINERCLASS: number;
    static EATTRIBUTE: number;
    static EATTRIBUTE_FEATURE_COUNT: number;
    static EATTRIBUTE_OPERATION_COUNT: number;
    static EATTRIBUTE_EANNOTATIONS: number;
    static EATTRIBUTE_NAME: number;
    static EATTRIBUTE_ORDERED: number;
    static EATTRIBUTE_UNIQUE: number;
    static EATTRIBUTE_LOWERBOUND: number;
    static EATTRIBUTE_UPPERBOUND: number;
    static EATTRIBUTE_MANY: number;
    static EATTRIBUTE_REQUIRED: number;
    static EATTRIBUTE_ETYPE: number;
    static EATTRIBUTE_EGENERICTYPE: number;
    static EATTRIBUTE_CHANGEABLE: number;
    static EATTRIBUTE_VOLATILE: number;
    static EATTRIBUTE_TRANSIENT: number;
    static EATTRIBUTE_DEFAULTVALUELITERAL: number;
    static EATTRIBUTE_DEFAULTVALUE: number;
    static EATTRIBUTE_UNSETTABLE: number;
    static EATTRIBUTE_DERIVED: number;
    static EATTRIBUTE_ECONTAININGCLASS: number;
    static EATTRIBUTE_ID: number;
    static EATTRIBUTE_EATTRIBUTETYPE: number;
    static EANNOTATION: number;
    static EANNOTATION_FEATURE_COUNT: number;
    static EANNOTATION_OPERATION_COUNT: number;
    static EANNOTATION_EANNOTATIONS: number;
    static EANNOTATION_SOURCE: number;
    static EANNOTATION_DETAILS: number;
    static EANNOTATION_EMODELELEMENT: number;
    static EANNOTATION_CONTENTS: number;
    static EANNOTATION_REFERENCES: number;
    static ECLASSIFIER: number;
    static ECLASSIFIER_FEATURE_COUNT: number;
    static ECLASSIFIER_OPERATION_COUNT: number;
    static ECLASSIFIER_EANNOTATIONS: number;
    static ECLASSIFIER_NAME: number;
    static ECLASSIFIER_INSTANCECLASSNAME: number;
    static ECLASSIFIER_INSTANCECLASS: number;
    static ECLASSIFIER_DEFAULTVALUE: number;
    static ECLASSIFIER_INSTANCETYPENAME: number;
    static ECLASSIFIER_EPACKAGE: number;
    static ECLASSIFIER_ETYPEPARAMETERS: number;
    static ECLASSIFIER___ISINSTANCE__OBJECT: number;
    static ECLASSIFIER___GETCLASSIFIERID: number;
    static ECLASS: number;
    static ECLASS_FEATURE_COUNT: number;
    static ECLASS_OPERATION_COUNT: number;
    static ECLASS_EANNOTATIONS: number;
    static ECLASS_NAME: number;
    static ECLASS_INSTANCECLASSNAME: number;
    static ECLASS_INSTANCECLASS: number;
    static ECLASS_DEFAULTVALUE: number;
    static ECLASS_INSTANCETYPENAME: number;
    static ECLASS_EPACKAGE: number;
    static ECLASS_ETYPEPARAMETERS: number;
    static ECLASS_ABSTRACT: number;
    static ECLASS_INTERFACE: number;
    static ECLASS_ESUPERTYPES: number;
    static ECLASS_EOPERATIONS: number;
    static ECLASS_EALLATTRIBUTES: number;
    static ECLASS_EALLREFERENCES: number;
    static ECLASS_EREFERENCES: number;
    static ECLASS_EATTRIBUTES: number;
    static ECLASS_EALLCONTAINMENTS: number;
    static ECLASS_EALLOPERATIONS: number;
    static ECLASS_EALLSTRUCTURALFEATURES: number;
    static ECLASS_EALLSUPERTYPES: number;
    static ECLASS_EIDATTRIBUTE: number;
    static ECLASS_ESTRUCTURALFEATURES: number;
    static ECLASS_EGENERICSUPERTYPES: number;
    static ECLASS_EALLGENERICSUPERTYPES: number;
    static ECLASS___ISSUPERTYPEOF__SOMECLASS: number;
    static ECLASS___GETFEATURECOUNT: number;
    static ECLASS___GETESTRUCTURALFEATURE__FEATUREID: number;
    static ECLASS___GETFEATUREID__FEATURE: number;
    static ECLASS___GETESTRUCTURALFEATURE__FEATURENAME: number;
    static ECLASS___GETOPERATIONCOUNT: number;
    static ECLASS___GETEOPERATION__OPERATIONID: number;
    static ECLASS___GETOPERATIONID__OPERATION: number;
    static ECLASS___GETOVERRIDE__OPERATION: number;
    static ECLASS___GETFEATURETYPE__FEATURE: number;
    static EDATATYPE: number;
    static EDATATYPE_FEATURE_COUNT: number;
    static EDATATYPE_OPERATION_COUNT: number;
    static EDATATYPE_EANNOTATIONS: number;
    static EDATATYPE_NAME: number;
    static EDATATYPE_INSTANCECLASSNAME: number;
    static EDATATYPE_INSTANCECLASS: number;
    static EDATATYPE_DEFAULTVALUE: number;
    static EDATATYPE_INSTANCETYPENAME: number;
    static EDATATYPE_EPACKAGE: number;
    static EDATATYPE_ETYPEPARAMETERS: number;
    static EDATATYPE_SERIALIZABLE: number;
    static EENUM: number;
    static EENUM_FEATURE_COUNT: number;
    static EENUM_OPERATION_COUNT: number;
    static EENUM_EANNOTATIONS: number;
    static EENUM_NAME: number;
    static EENUM_INSTANCECLASSNAME: number;
    static EENUM_INSTANCECLASS: number;
    static EENUM_DEFAULTVALUE: number;
    static EENUM_INSTANCETYPENAME: number;
    static EENUM_EPACKAGE: number;
    static EENUM_ETYPEPARAMETERS: number;
    static EENUM_SERIALIZABLE: number;
    static EENUM_ELITERALS: number;
    static EENUM___GETEENUMLITERAL__NAME: number;
    static EENUM___GETEENUMLITERAL__VALUE: number;
    static EENUM___GETEENUMLITERALBYLITERAL__LITERAL: number;
    static EENUMLITERAL: number;
    static EENUMLITERAL_FEATURE_COUNT: number;
    static EENUMLITERAL_OPERATION_COUNT: number;
    static EENUMLITERAL_EANNOTATIONS: number;
    static EENUMLITERAL_NAME: number;
    static EENUMLITERAL_VALUE: number;
    static EENUMLITERAL_INSTANCE: number;
    static EENUMLITERAL_LITERAL: number;
    static EENUMLITERAL_EENUM: number;
    static EFACTORY: number;
    static EFACTORY_FEATURE_COUNT: number;
    static EFACTORY_OPERATION_COUNT: number;
    static EFACTORY_EANNOTATIONS: number;
    static EFACTORY_EPACKAGE: number;
    static EFACTORY___CREATE__ECLASS: number;
    static EFACTORY___CREATEFROMSTRING__EDATATYPE__LITERALVALUE: number;
    static EFACTORY___CONVERTTOSTRING__EDATATYPE__INSTANCEVALUE: number;
    static EOBJECT: number;
    static EOBJECT_FEATURE_COUNT: number;
    static EOBJECT_OPERATION_COUNT: number;
    static EOBJECT___ECLASS: number;
    static EOBJECT___EISPROXY: number;
    static EOBJECT___ERESOURCE: number;
    static EOBJECT___ECONTAINER: number;
    static EOBJECT___ECONTAININGFEATURE: number;
    static EOBJECT___ECONTAINMENTFEATURE: number;
    static EOBJECT___ECONTENTS: number;
    static EOBJECT___EALLCONTENTS: number;
    static EOBJECT___ECROSSREFERENCES: number;
    static EOBJECT___EGET__FEATURE: number;
    static EOBJECT___EGET__FEATURE__RESOLVE: number;
    static EOBJECT___ESET__FEATURE__NEWVALUE: number;
    static EOBJECT___EISSET__FEATURE: number;
    static EOBJECT___EUNSET__FEATURE: number;
    static EOBJECT___EINVOKE__OPERATION__ARGUMENTS: number;
    static EOPERATION: number;
    static EOPERATION_FEATURE_COUNT: number;
    static EOPERATION_OPERATION_COUNT: number;
    static EOPERATION_EANNOTATIONS: number;
    static EOPERATION_NAME: number;
    static EOPERATION_ORDERED: number;
    static EOPERATION_UNIQUE: number;
    static EOPERATION_LOWERBOUND: number;
    static EOPERATION_UPPERBOUND: number;
    static EOPERATION_MANY: number;
    static EOPERATION_REQUIRED: number;
    static EOPERATION_ETYPE: number;
    static EOPERATION_EGENERICTYPE: number;
    static EOPERATION_ECONTAININGCLASS: number;
    static EOPERATION_ETYPEPARAMETERS: number;
    static EOPERATION_EPARAMETERS: number;
    static EOPERATION_EEXCEPTIONS: number;
    static EOPERATION_EGENERICEXCEPTIONS: number;
    static EOPERATION___GETOPERATIONID: number;
    static EOPERATION___ISOVERRIDEOF__SOMEOPERATION: number;
    static EPACKAGE: number;
    static EPACKAGE_FEATURE_COUNT: number;
    static EPACKAGE_OPERATION_COUNT: number;
    static EPACKAGE_EANNOTATIONS: number;
    static EPACKAGE_NAME: number;
    static EPACKAGE_NSURI: number;
    static EPACKAGE_NSPREFIX: number;
    static EPACKAGE_EFACTORYINSTANCE: number;
    static EPACKAGE_ECLASSIFIERS: number;
    static EPACKAGE_ESUBPACKAGES: number;
    static EPACKAGE_ESUPERPACKAGE: number;
    static EPACKAGE___GETECLASSIFIER__NAME: number;
    static EPARAMETER: number;
    static EPARAMETER_FEATURE_COUNT: number;
    static EPARAMETER_OPERATION_COUNT: number;
    static EPARAMETER_EANNOTATIONS: number;
    static EPARAMETER_NAME: number;
    static EPARAMETER_ORDERED: number;
    static EPARAMETER_UNIQUE: number;
    static EPARAMETER_LOWERBOUND: number;
    static EPARAMETER_UPPERBOUND: number;
    static EPARAMETER_MANY: number;
    static EPARAMETER_REQUIRED: number;
    static EPARAMETER_ETYPE: number;
    static EPARAMETER_EGENERICTYPE: number;
    static EPARAMETER_EOPERATION: number;
    static EREFERENCE: number;
    static EREFERENCE_FEATURE_COUNT: number;
    static EREFERENCE_OPERATION_COUNT: number;
    static EREFERENCE_EANNOTATIONS: number;
    static EREFERENCE_NAME: number;
    static EREFERENCE_ORDERED: number;
    static EREFERENCE_UNIQUE: number;
    static EREFERENCE_LOWERBOUND: number;
    static EREFERENCE_UPPERBOUND: number;
    static EREFERENCE_MANY: number;
    static EREFERENCE_REQUIRED: number;
    static EREFERENCE_ETYPE: number;
    static EREFERENCE_EGENERICTYPE: number;
    static EREFERENCE_CHANGEABLE: number;
    static EREFERENCE_VOLATILE: number;
    static EREFERENCE_TRANSIENT: number;
    static EREFERENCE_DEFAULTVALUELITERAL: number;
    static EREFERENCE_DEFAULTVALUE: number;
    static EREFERENCE_UNSETTABLE: number;
    static EREFERENCE_DERIVED: number;
    static EREFERENCE_ECONTAININGCLASS: number;
    static EREFERENCE_CONTAINMENT: number;
    static EREFERENCE_CONTAINER: number;
    static EREFERENCE_RESOLVEPROXIES: number;
    static EREFERENCE_EOPPOSITE: number;
    static EREFERENCE_EREFERENCETYPE: number;
    static EREFERENCE_EKEYS: number;
    static ESTRINGTOSTRINGMAPENTRY: number;
    static ESTRINGTOSTRINGMAPENTRY_FEATURE_COUNT: number;
    static ESTRINGTOSTRINGMAPENTRY_OPERATION_COUNT: number;
    static ESTRINGTOSTRINGMAPENTRY_KEY: number;
    static ESTRINGTOSTRINGMAPENTRY_VALUE: number;
    static EGENERICTYPE: number;
    static EGENERICTYPE_FEATURE_COUNT: number;
    static EGENERICTYPE_OPERATION_COUNT: number;
    static EGENERICTYPE_EUPPERBOUND: number;
    static EGENERICTYPE_ETYPEARGUMENTS: number;
    static EGENERICTYPE_ERAWTYPE: number;
    static EGENERICTYPE_ELOWERBOUND: number;
    static EGENERICTYPE_ETYPEPARAMETER: number;
    static EGENERICTYPE_ECLASSIFIER: number;
    static EGENERICTYPE___ISINSTANCE__OBJECT: number;
    static ETYPEPARAMETER: number;
    static ETYPEPARAMETER_FEATURE_COUNT: number;
    static ETYPEPARAMETER_OPERATION_COUNT: number;
    static ETYPEPARAMETER_EANNOTATIONS: number;
    static ETYPEPARAMETER_NAME: number;
    static ETYPEPARAMETER_EBOUNDS: number;
    static EBIGDECIMAL: number;
    static EBIGINTEGER: number;
    static EBOOLEAN: number;
    static EBOOLEANOBJECT: number;
    static EBYTE: number;
    static EBYTEARRAY: number;
    static EBYTEOBJECT: number;
    static ECHAR: number;
    static ECHARACTEROBJECT: number;
    static EDATE: number;
    static EDIAGNOSTICCHAIN: number;
    static EDOUBLE: number;
    static EDOUBLEOBJECT: number;
    static EELIST: number;
    static EENUMERATOR: number;
    static EFEATUREMAP: number;
    static EFEATUREMAPENTRY: number;
    static EFLOAT: number;
    static EFLOATOBJECT: number;
    static EINT: number;
    static EINTEGEROBJECT: number;
    static EJAVACLASS: number;
    static EJAVAOBJECT: number;
    static ELONG: number;
    static ELONGOBJECT: number;
    static EMAP: number;
    static ERESOURCE: number;
    static ERESOURCESET: number;
    static ESHORT: number;
    static ESHORTOBJECT: number;
    static ESTRING: number;
    static ETREEITERATOR: number;
    static EINVOCATIONTARGETEXCEPTION: number;
    static eINSTANCE: EcorePackage;
    getEModelElement: () => EClass;
    getEModelElement_EAnnotations: () => EReference;
    getEModelElement__GetEAnnotation__Source: () => EOperation;
    getENamedElement: () => EClass;
    getENamedElement_Name: () => EAttribute;
    getETypedElement: () => EClass;
    getETypedElement_Ordered: () => EAttribute;
    getETypedElement_Unique: () => EAttribute;
    getETypedElement_LowerBound: () => EAttribute;
    getETypedElement_UpperBound: () => EAttribute;
    getETypedElement_Many: () => EAttribute;
    getETypedElement_Required: () => EAttribute;
    getETypedElement_EType: () => EReference;
    getETypedElement_EGenericType: () => EReference;
    getEStructuralFeature: () => EClass;
    getEStructuralFeature_Changeable: () => EAttribute;
    getEStructuralFeature_Volatile: () => EAttribute;
    getEStructuralFeature_Transient: () => EAttribute;
    getEStructuralFeature_DefaultValueLiteral: () => EAttribute;
    getEStructuralFeature_DefaultValue: () => EAttribute;
    getEStructuralFeature_Unsettable: () => EAttribute;
    getEStructuralFeature_Derived: () => EAttribute;
    getEStructuralFeature_EContainingClass: () => EReference;
    getEStructuralFeature__GetFeatureID__: () => EOperation;
    getEStructuralFeature__GetContainerClass__: () => EOperation;
    getEAttribute: () => EClass;
    getEAttribute_ID: () => EAttribute;
    getEAttribute_EAttributeType: () => EReference;
    getEAnnotation_: () => EClass;
    getEAnnotation_Source: () => EAttribute;
    getEAnnotation_Details: () => EReference;
    getEAnnotation_EModelElement: () => EReference;
    getEAnnotation_Contents: () => EReference;
    getEAnnotation_References: () => EReference;
    getEClassifier_: () => EClass;
    getEClassifier_InstanceClassName: () => EAttribute;
    getEClassifier_InstanceClass: () => EAttribute;
    getEClassifier_DefaultValue: () => EAttribute;
    getEClassifier_InstanceTypeName: () => EAttribute;
    getEClassifier_EPackage: () => EReference;
    getEClassifier_ETypeParameters: () => EReference;
    getEClassifier__IsInstance__Object: () => EOperation;
    getEClassifier__GetClassifierID__: () => EOperation;
    getEClass: () => EClass;
    getEClass_Abstract: () => EAttribute;
    getEClass_Interface: () => EAttribute;
    getEClass_ESuperTypes: () => EReference;
    getEClass_EOperations: () => EReference;
    getEClass_EAllAttributes: () => EReference;
    getEClass_EAllReferences: () => EReference;
    getEClass_EReferences: () => EReference;
    getEClass_EAttributes: () => EReference;
    getEClass_EAllContainments: () => EReference;
    getEClass_EAllOperations: () => EReference;
    getEClass_EAllStructuralFeatures: () => EReference;
    getEClass_EAllSuperTypes: () => EReference;
    getEClass_EIDAttribute: () => EReference;
    getEClass_EStructuralFeatures: () => EReference;
    getEClass_EGenericSuperTypes: () => EReference;
    getEClass_EAllGenericSuperTypes: () => EReference;
    getEClass__IsSuperTypeOf__SomeClass: () => EOperation;
    getEClass__GetFeatureCount__: () => EOperation;
    getEClass__GetEStructuralFeature__FeatureID: () => EOperation;
    getEClass__GetFeatureID__Feature: () => EOperation;
    getEClass__GetEStructuralFeature__FeatureName: () => EOperation;
    getEClass__GetOperationCount__: () => EOperation;
    getEClass__GetEOperation__OperationID: () => EOperation;
    getEClass__GetOperationID__Operation: () => EOperation;
    getEClass__GetOverride__Operation: () => EOperation;
    getEClass__GetFeatureType__Feature: () => EOperation;
    getEDataType: () => EClass;
    getEDataType_Serializable: () => EAttribute;
    getEEnum: () => EClass;
    getEEnum_ELiterals: () => EReference;
    getEEnum__GetEEnumLiteral__Name: () => EOperation;
    getEEnum__GetEEnumLiteral__Value: () => EOperation;
    getEEnum__GetEEnumLiteralByLiteral__Literal: () => EOperation;
    getEEnumLiteral: () => EClass;
    getEEnumLiteral_Value: () => EAttribute;
    getEEnumLiteral_Instance: () => EAttribute;
    getEEnumLiteral_Literal: () => EAttribute;
    getEEnumLiteral_EEnum: () => EReference;
    getEFactory: () => EClass;
    getEFactory_EPackage: () => EReference;
    getEFactory__Create__EClass: () => EOperation;
    getEFactory__CreateFromString__EDataType__LiteralValue: () => EOperation;
    getEFactory__ConvertToString__EDataType__InstanceValue: () => EOperation;
    getEObject: () => EClass;
    getEObject__EClass__: () => EOperation;
    getEObject__EIsProxy__: () => EOperation;
    getEObject__EResource__: () => EOperation;
    getEObject__EContainer__: () => EOperation;
    getEObject__EContainingFeature__: () => EOperation;
    getEObject__EContainmentFeature__: () => EOperation;
    getEObject__EContents__: () => EOperation;
    getEObject__EAllContents__: () => EOperation;
    getEObject__ECrossReferences__: () => EOperation;
    getEObject__EGet__Feature: () => EOperation;
    getEObject__EGet__Feature__Resolve: () => EOperation;
    getEObject__ESet__Feature__NewValue: () => EOperation;
    getEObject__EIsSet__Feature: () => EOperation;
    getEObject__EUnset__Feature: () => EOperation;
    getEObject__EInvoke__Operation__Arguments: () => EOperation;
    getEOperation: () => EClass;
    getEOperation_EContainingClass: () => EReference;
    getEOperation_ETypeParameters: () => EReference;
    getEOperation_EParameters: () => EReference;
    getEOperation_EExceptions: () => EReference;
    getEOperation_EGenericExceptions: () => EReference;
    getEOperation__GetOperationID__: () => EOperation;
    getEOperation__IsOverrideOf__SomeOperation: () => EOperation;
    getEPackage: () => EClass;
    getEPackage_NsURI: () => EAttribute;
    getEPackage_NsPrefix: () => EAttribute;
    getEPackage_EFactoryInstance: () => EReference;
    getEPackage_EClassifiers: () => EReference;
    getEPackage_ESubpackages: () => EReference;
    getEPackage_ESuperPackage: () => EReference;
    getEPackage__GetEClassifier__Name: () => EOperation;
    getEParameter: () => EClass;
    getEParameter_EOperation: () => EReference;
    getEReference: () => EClass;
    getEReference_Containment: () => EAttribute;
    getEReference_Container: () => EAttribute;
    getEReference_ResolveProxies: () => EAttribute;
    getEReference_EOpposite: () => EReference;
    getEReference_EReferenceType: () => EReference;
    getEReference_EKeys: () => EReference;
    getEStringToStringMapEntry: () => EClass;
    getEStringToStringMapEntry_Key: () => EAttribute;
    getEStringToStringMapEntry_Value: () => EAttribute;
    getEGenericType: () => EClass;
    getEGenericType_EUpperBound: () => EReference;
    getEGenericType_ETypeArguments: () => EReference;
    getEGenericType_ERawType: () => EReference;
    getEGenericType_ELowerBound: () => EReference;
    getEGenericType_ETypeParameter: () => EReference;
    getEGenericType_EClassifier: () => EReference;
    getEGenericType__IsInstance__Object: () => EOperation;
    getETypeParameter: () => EClass;
    getETypeParameter_EBounds: () => EReference;
    getEBigDecimal: () => EDataType;
    getEBigInteger: () => EDataType;
    getEBoolean: () => EDataType;
    getEBooleanObject: () => EDataType;
    getEByte: () => EDataType;
    getEByteArray: () => EDataType;
    getEByteObject: () => EDataType;
    getEChar: () => EDataType;
    getECharacterObject: () => EDataType;
    getEDate: () => EDataType;
    getEDiagnosticChain: () => EDataType;
    getEDouble: () => EDataType;
    getEDoubleObject: () => EDataType;
    getEEList: () => EDataType;
    getEEnumerator: () => EDataType;
    getEFeatureMap: () => EDataType;
    getEFeatureMapEntry: () => EDataType;
    getEFloat: () => EDataType;
    getEFloatObject: () => EDataType;
    getEInt: () => EDataType;
    getEIntegerObject: () => EDataType;
    getEJavaClass: () => EDataType;
    getEJavaObject: () => EDataType;
    getELong: () => EDataType;
    getELongObject: () => EDataType;
    getEMap: () => EDataType;
    getEResource: () => EDataType;
    getEResourceSet: () => EDataType;
    getEShort: () => EDataType;
    getEShortObject: () => EDataType;
    getEString: () => EDataType;
    getETreeIterator: () => EDataType;
    getEInvocationTargetException: () => EDataType;
}
